config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users do
    resources :tags, only: %i[create destroy new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord

  has_many :tags

  validates :first_name, presence: true, on: :create
  validates :last_name, presence: true, on: :create
  validates :email, presence: true, on: :create


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :find_user, only: %i[new create]
  before_action :set_tag, only: :destroy

  def create
    @tag = @user.tags.new(tag_params)

    if @tag.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @tag.destroy
    redirect_to user_path(@tag)
  end

  def new
    @tag = @user.tags.new
  end

  private

  def tag_params
    params.require(:tag).permit(:title, :user_id)
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def find_user
    @user = User.find(params[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: %i[show destroy update edit]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def new
    @user = User.new
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :image_url, :workspace, :about)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Portfolio
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body
    = render 'shared/header'
    div class="container"
      = yield
    = render 'shared/footer'

app/views/shared/_footer.html.slim
footer class="page-footer fixed-bottom font-small bg-dark pt-4 text-white"

  div class="container-fluid text-center text-md-left"

    div class="row"

      div class="col-md-6 mt-md-0 mt-3"

        h5 Footer Content

      div
        h5 class="clearfix w-100 d-md-none pb-3"

      div class="col-md-3 mb-md-0 mb-3"
        h5 class="text-uppercase" Links

        ul class="list-unstyled"
          li
            a href="#!" Link 1
      div
      div class="col-md-3 mb-md-0 mb-3"

        h5 class="text-uppercase" Links

        ul class="list-unstyled"
          li
            a href="#!" Link 1

  div class="footer-copyright text-center py-3" © 2019 Copyright: Malinin Mikhail

app/views/shared/_header.html.slim
nav class="navbar navbar-dark bg-dark"
  h1
    == link_to "Portfolio", root_path
  p
    == link_to "Create portfolio", new_user_path, class: "btn btn-primary"

app/views/tags/_form.html.slim
= bootstrap_form_with model: [:user, @tag], local: true do |form|
  = form.text_field :title, id: :user_tag, class: "form-control"
  = form.submit

app/views/tags/_tag.html.slim
span class="inline border"
  =tag.title
  =link_to "X", user_tag_path(tag), method: :delete

app/views/tags/new.html.slim
div class="row justify-content-center mt-3"
  div class="col col-md-4"
    div class="card border-primary"
      div class="card-body"
        == render 'form'
      = link_to 'back', users_path, class: "btn btn-primary"

app/views/users/_form.html.slim
= bootstrap_form_with model: @user, local: true do |form|
  = form.text_field :first_name, id: :user_first_name, class: "form-control"
  = form.text_field :last_name, id: :user_last_name, class: "form-control"
  = form.text_field :email, id: :user_email, class: "form-control"
  = form.text_field :image_url, id: :user_image, class: "form-control"
  = form.text_area :about, id: :user_about, class: "form-control"
  = form.text_field :workplace, id: :user_workplace, class: "form-control"
  = form.submit

app/views/users/_user.html.slim
p
= user.first_name
br
= user.last_name
br
= user.email
br
= user.workplace
br
= link_to 'Show portfolio', user_path(user)

app/views/users/edit.html.slim
div class="row justify-content-center mt-3"
  div class="col col-md-4"
      h1 Editing portfolio
      div class="card border-primary"
          div class="card-body"
            = render 'form'
          = link_to 'back', users_path, class: "btn btn-primary"

app/views/users/index.html.slim
h2 All portfolios
= render @users

app/views/users/new.html.slim
div class="row justify-content-center mt-3"
  div class="col col-md-4"
    div class="card border-primary"
      div class="card-body"
        == render 'form'
      = link_to 'back', users_path, class: "btn btn-primary"

app/views/users/show.html.slim
  div
    = image_tag @user.image_url, title: @user.first_name, class: "rounded-circle"
  div class="info"
    p
      | First name:
      br
      = @user.first_name
    p
      | Last name:
      br
      = @user.last_name
    p
      | Email:
      br
      = @user.email
    p
      | About:
      br
      = @user.about
    p
      | Workplace:
      = @user.workplace
    p
      |User tags:
      - if @user.tags.present?
      = render @user.tags



    p
    span class="inline"
    = link_to "Create tag", new_user_tag_path(@user), class: "d-inline p-2 bg-primary text-white"
    = link_to 'Delete portfolio', user_path(@user), method: :delete, data: { confirm: "Are you shure?" }, class: "d-inline p-2 bg-primary text-white"
    = link_to 'Edit', edit_user_path(@user), class: "d-inline p-2 bg-primary text-white"
    = link_to 'Back', users_path, class: "d-inline p-2 bg-primary text-white"